language: csharp
solution: Source/Roguicka/Roguicka.sln
install:
  - nuget restore Source/Roguicka/Roguicka.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Source/Roguicka/Roguicka.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Source/Roguicka/Roguicka.Tests/bin/Release/Roguicka.Tests.dll
